package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to
// the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/example/graphql-api/internal/datasource"
	"github.com/example/graphql-api/internal/graphql/generated"
	"github.com/example/graphql-api/internal/graphql/scalar"
)

// Starrocks is the resolver for the starrocks field.
func (r *queryResolver) Starrocks(
	ctx context.Context,
	table string,
	fields []string,
	filters []*generated.StarRocksFilter,
	orderBy []*generated.StarRocksOrderBy,
	first *int,
	after *string,
	offset *int,
	limit *int,
) (*generated.StarRocksConnection, error) {
	req := buildStarRocksQueryRequest(
		fields, filters, orderBy, first, after, offset, limit,
	)
	req.NeedCount = fieldRequested(ctx, "totalCount")

	result, err := r.DSManager.ExecuteWithRetry(
		ctx, findStarRocksDS(r), datasource.QueryRequest(req),
	)
	if err != nil {
		return nil, err
	}

	var warnings []string
	warnings = append(warnings, result.Warnings...)

	maxRows := r.GraphQLConfig.MaxResultRows
	data := result.Data
	if maxRows > 0 && len(data) > maxRows {
		warnings = append(warnings, fmt.Sprintf(
			"Result set truncated: returned %d rows out of %d (max_result_rows=%d)",
			maxRows, len(data), maxRows,
		))
		data = data[:maxRows]
	}

	conn := buildStarRocksConnection(data, result.TotalCount, offset, first)
	setExtensionWarnings(ctx, warnings)
	return conn, nil
}

// PrometheusInstant is the resolver for the prometheusInstant field.
func (r *queryResolver) PrometheusInstant(
	ctx context.Context,
	query string,
	timeArg *scalar.DateTime,
	filters []*generated.PrometheusLabelFilter,
) (*generated.PrometheusInstantResult, error) {
	req := buildPrometheusInstantRequest(query, timeArg, filters)

	result, err := r.DSManager.ExecuteWithRetry(
		ctx, findPrometheusDS(r), datasource.QueryRequest(req),
	)
	if err != nil {
		return nil, err
	}

	setExtensionWarnings(ctx, result.Warnings)
	return convertToInstantResult(result), nil
}

// PrometheusRange is the resolver for the prometheusRange field.
func (r *queryResolver) PrometheusRange(
	ctx context.Context,
	query string,
	startTime scalar.DateTime,
	endTime scalar.DateTime,
	step string,
	filters []*generated.PrometheusLabelFilter,
) (*generated.PrometheusRangeResult, error) {
	req := buildPrometheusRangeRequest(
		query, startTime, endTime, step, filters,
	)

	result, err := r.DSManager.ExecuteWithRetry(
		ctx, findPrometheusDS(r), datasource.QueryRequest(req),
	)
	if err != nil {
		return nil, err
	}

	setExtensionWarnings(ctx, result.Warnings)
	return convertToRangeResult(result), nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver {
	return &queryResolver{r}
}

type queryResolver struct{ *Resolver }
