package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/example/graphql-api/internal/graphql/generated"
)

// ClearCache is the resolver for the clearCache field.
// It clears result cache entries only (cache: prefix), not APQ cache (apq: prefix).
// Authorization for the "mutation" operation is enforced by the auth middleware (task 14).
func (r *mutationResolver) ClearCache(ctx context.Context, datasource *string) (bool, error) {
	// If cache is disabled (CacheClearer is nil), treat as no-op success.
	if r.CacheClearer == nil {
		return true, nil
	}

	if datasource != nil {
		if err := r.CacheClearer.ClearByDatasource(ctx, *datasource); err != nil {
			return false, fmt.Errorf("failed to clear cache for datasource %q: %w", *datasource, err)
		}
		return true, nil
	}

	if err := r.CacheClearer.ClearAll(ctx); err != nil {
		return false, fmt.Errorf("failed to clear all cache: %w", err)
	}
	return true, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
