// Copyright 2024-2026 mountainKing Contributors
// Licensed under the Apache License, Version 2.0
// See LICENSE file for details.

package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to
// the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	apierrors "github.com/michaelwang123/mountainKing/internal/errors"
	"github.com/michaelwang123/mountainKing/internal/graphql/generated"
	"github.com/michaelwang123/mountainKing/internal/graphql/scalar"
	"github.com/michaelwang123/mountainKing/internal/template"
)

// TemplateQuery is the resolver for the templateQuery field.
func (r *queryResolver) TemplateQuery(ctx context.Context, templateName string, parameters scalar.JSON, fields []string, first *int, offset *int, orderBy []*generated.TemplateOrderBy) (*generated.TemplateQueryConnection, error) {
	// 1. Check if TemplateEngine is initialised (sql_templates.enabled).
	if r.TemplateEngine == nil {
		return nil, apierrors.ValidationError(
			apierrors.ErrValidationTemplateNotFound,
			fmt.Sprintf("template %q not found", templateName),
		)
	}

	// 2. Build TemplateQueryRequest.
	req := &template.TemplateQueryRequest{
		TemplateName: templateName,
		Parameters:   convertJSONToMap(parameters),
		Fields:       fields,
		First:        first,
		Offset:       offset,
		OrderBy:      convertOrderBy(orderBy),
		NeedCount:    fieldRequested(ctx, "totalCount"),
		SkipCache:    skipCacheRequested(ctx),
	}

	// 3. Execute template query.
	result, err := r.TemplateEngine.Execute(ctx, req)
	if err != nil {
		return nil, err
	}

	// 4. Result truncation (over-fetch + max_result_rows).
	maxRows := r.GraphQLConfig.MaxResultRows
	data := result.Data
	originalLen := len(data)

	// Over-fetch truncation: wrapWithPagination requested first+1 rows,
	// truncate back to first.
	if first != nil && len(data) > *first {
		data = data[:*first]
	}

	var warnings []string
	warnings = append(warnings, result.Warnings...)
	if maxRows > 0 && len(data) > maxRows {
		warnings = append(warnings, fmt.Sprintf(
			"Result set truncated: returned %d rows out of %d (max_result_rows=%d)",
			maxRows, len(data), maxRows,
		))
		data = data[:maxRows]
	}

	// 5. Build TemplateQueryConnection.
	conn := buildTemplateQueryConnection(data, originalLen, result.TotalCount, offset, first)
	setExtensionWarnings(ctx, warnings)
	return conn, nil
}

// TemplateList is the resolver for the templateList field.
func (r *queryResolver) TemplateList(ctx context.Context, first *int, offset *int) ([]*generated.TemplateInfo, error) {
	if r.TemplateEngine == nil {
		return []*generated.TemplateInfo{}, nil
	}

	infos := r.TemplateEngine.ListTemplates(first, offset)
	result := make([]*generated.TemplateInfo, 0, len(infos))
	for _, info := range infos {
		params := make([]*generated.TemplateParameterInfo, 0, len(info.Parameters))
		for _, p := range info.Parameters {
			params = append(params, &generated.TemplateParameterInfo{
				Name:         p.Name,
				Type:         p.Type,
				Required:     p.Required,
				DefaultValue: p.DefaultValue,
			})
		}
		result = append(result, &generated.TemplateInfo{
			Name:         info.Name,
			Description:  info.Description,
			CountEnabled: info.CountEnabled,
			Parameters:   params,
		})
	}
	return result, nil
}

// ReloadTemplates is the resolver for the reloadTemplates field.
func (r *mutationResolver) ReloadTemplates(ctx context.Context) (*generated.ReloadTemplatesResult, error) {
	if r.TemplateEngine == nil {
		return &generated.ReloadTemplatesResult{
			SuccessCount: 0,
			Failures:     []*generated.TemplateLoadFailure{},
			Duration:     "0s",
		}, nil
	}

	result, err := r.TemplateEngine.Reload(ctx, true)
	if err != nil {
		return nil, err
	}
	return convertReloadResult(result), nil
}

// ---------------------------------------------------------------------------
// Template resolver helper functions
// ---------------------------------------------------------------------------

// convertJSONToMap converts a scalar.JSON value to map[string]interface{}.
// Returns nil if the input is nil (no parameters provided).
func convertJSONToMap(j scalar.JSON) map[string]interface{} {
	if j == nil {
		return nil
	}
	result := make(map[string]interface{}, len(j))
	for k, v := range j {
		result[k] = v
	}
	return result
}

// convertOrderBy converts GraphQL TemplateOrderBy inputs to internal
// TemplateOrderByParam values.
func convertOrderBy(orderBy []*generated.TemplateOrderBy) []template.TemplateOrderByParam {
	if len(orderBy) == 0 {
		return nil
	}
	result := make([]template.TemplateOrderByParam, 0, len(orderBy))
	for _, o := range orderBy {
		if o == nil {
			continue
		}
		result = append(result, template.TemplateOrderByParam{
			Field:     o.Field,
			Direction: o.Direction.String(),
		})
	}
	return result
}

// skipCacheRequested checks if the client requested cache bypass via
// extensions.cache=false in the GraphQL operation context.
func skipCacheRequested(ctx context.Context) bool {
	oc := graphql.GetOperationContext(ctx)
	if oc == nil {
		return false
	}
	cacheVal, ok := oc.Extensions["cache"]
	if !ok {
		return false
	}
	b, ok := cacheVal.(bool)
	return ok && !b
}

// buildTemplateQueryConnection builds a TemplateQueryConnection from query
// result data. It uses the over-fetch strategy: the pagination wrapper
// requested first+1 rows, so if originalLen > first, hasNextPage is true.
func buildTemplateQueryConnection(
	data []map[string]interface{},
	originalLen int,
	totalCount *int64,
	offset *int,
	first *int,
) *generated.TemplateQueryConnection {
	nodes := make([]scalar.JSON, 0, len(data))
	for _, row := range data {
		nodes = append(nodes, scalar.JSON(row))
	}

	hasNextPage := first != nil && originalLen > *first
	hasPreviousPage := offset != nil && *offset > 0

	tc := 0
	if totalCount != nil {
		tc = int(*totalCount)
	}

	return &generated.TemplateQueryConnection{
		Nodes: nodes,
		PageInfo: &generated.PageInfo{
			HasNextPage:     hasNextPage,
			HasPreviousPage: hasPreviousPage,
		},
		TotalCount: tc,
	}
}

// convertReloadResult converts an internal template.ReloadResult to the
// generated GraphQL ReloadTemplatesResult type.
func convertReloadResult(r *template.ReloadResult) *generated.ReloadTemplatesResult {
	failures := make([]*generated.TemplateLoadFailure, 0, len(r.Failures))
	for _, f := range r.Failures {
		failures = append(failures, &generated.TemplateLoadFailure{
			Name:  f.Name,
			Error: f.Error,
		})
	}
	return &generated.ReloadTemplatesResult{
		SuccessCount: r.SuccessCount,
		Failures:     failures,
		Duration:     r.Duration.String(),
	}
}
