package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	apierrors "github.com/michaelwang123/mountainKing/internal/errors"
	"github.com/michaelwang123/mountainKing/internal/graphql/generated"
	"github.com/michaelwang123/mountainKing/internal/graphql/scalar"
	"github.com/michaelwang123/mountainKing/internal/template"
)

// ReloadTemplates is the resolver for the reloadTemplates field.
func (r *mutationResolver) ReloadTemplates(ctx context.Context) (*generated.ReloadTemplatesResult, error) {
	if r.TemplateEngine == nil {
		return &generated.ReloadTemplatesResult{
			SuccessCount: 0,
			Failures:     []*generated.TemplateLoadFailure{},
			Duration:     "0s",
		}, nil
	}

	result, err := r.TemplateEngine.Reload(ctx, true)
	if err != nil {
		return nil, err
	}
	return convertReloadResult(result), nil
}

// TemplateQuery is the resolver for the templateQuery field.
func (r *queryResolver) TemplateQuery(ctx context.Context, templateName string, parameters scalar.JSON, fields []string, first *int, offset *int, orderBy []*generated.TemplateOrderBy) (*generated.TemplateQueryConnection, error) {
	// 1. Check if TemplateEngine is initialised (sql_templates.enabled).
	if r.TemplateEngine == nil {
		return nil, apierrors.ValidationError(
			apierrors.ErrValidationTemplateNotFound,
			fmt.Sprintf("template %q not found", templateName),
		)
	}

	// 2. Build TemplateQueryRequest.
	req := &template.TemplateQueryRequest{
		TemplateName: templateName,
		Parameters:   convertJSONToMap(parameters),
		Fields:       fields,
		First:        first,
		Offset:       offset,
		OrderBy:      convertOrderBy(orderBy),
		NeedCount:    fieldRequested(ctx, "totalCount"),
		SkipCache:    skipCacheRequested(ctx),
	}

	// 3. Execute template query.
	result, err := r.TemplateEngine.Execute(ctx, req)
	if err != nil {
		return nil, err
	}

	// 4. Result truncation (over-fetch + max_result_rows).
	maxRows := r.GraphQLConfig.MaxResultRows
	data := result.Data
	originalLen := len(data)

	// Over-fetch truncation: wrapWithPagination requested first+1 rows,
	// truncate back to first.
	if first != nil && len(data) > *first {
		data = data[:*first]
	}

	var warnings []string
	warnings = append(warnings, result.Warnings...)
	if maxRows > 0 && len(data) > maxRows {
		warnings = append(warnings, fmt.Sprintf(
			"Result set truncated: returned %d rows out of %d (max_result_rows=%d)",
			maxRows, len(data), maxRows,
		))
		data = data[:maxRows]
	}

	// 5. Build TemplateQueryConnection.
	conn := buildTemplateQueryConnection(data, originalLen, result.TotalCount, offset, first)
	setExtensionWarnings(ctx, warnings)
	return conn, nil
}

// TemplateList is the resolver for the templateList field.
func (r *queryResolver) TemplateList(ctx context.Context, first *int, offset *int) ([]*generated.TemplateInfo, error) {
	if r.TemplateEngine == nil {
		return []*generated.TemplateInfo{}, nil
	}

	infos := r.TemplateEngine.ListTemplates(first, offset)
	result := make([]*generated.TemplateInfo, 0, len(infos))
	for _, info := range infos {
		params := make([]*generated.TemplateParameterInfo, 0, len(info.Parameters))
		for _, p := range info.Parameters {
			params = append(params, &generated.TemplateParameterInfo{
				Name:         p.Name,
				Type:         p.Type,
				Required:     p.Required,
				DefaultValue: p.DefaultValue,
			})
		}
		result = append(result, &generated.TemplateInfo{
			Name:         info.Name,
			Description:  info.Description,
			CountEnabled: info.CountEnabled,
			Parameters:   params,
		})
	}
	return result, nil
}
