// Copyright 2024-2026 mountainKing Contributors
// Licensed under the Apache License, Version 2.0
// See LICENSE file for details.

package prometheus

import (
	"math"
	"testing"

	apierrors "github.com/michaelwang123/mountainKing/internal/errors"
	"pgregory.net/rapid"
)

// promResultTypeMapping defines the expected Prometheus result type �?GraphQL type mappings.
var promResultTypeMapping = map[PrometheusResultType]GraphQLTypeName{
	ResultTypeScalar: GQLFloat,
	ResultTypeString: GQLString,
	ResultTypeVector: GQLPrometheusVector,
	ResultTypeMatrix: GQLPrometheusMatrix,
}

// knownPromResultTypes returns a slice of all known Prometheus result types.
func knownPromResultTypes() []PrometheusResultType {
	return []PrometheusResultType{
		ResultTypeScalar,
		ResultTypeString,
		ResultTypeVector,
		ResultTypeMatrix,
	}
}

// TestProperty21_PrometheusTypeMapping validates that for any Prometheus result type
// (scalar, string, vector, matrix), MapResultType returns the correct GraphQL type.
// Unknown types fall back to String.
//
// Feature: graphql-multi-datasource-api, Property 21: Prometheus 类型映射
// **Validates: Requirements 5.8**
func TestProperty21_PrometheusTypeMapping(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		types := knownPromResultTypes()
		idx := rapid.IntRange(0, len(types)-1).Draw(t, "typeIdx")
		rt := types[idx]
		expected := promResultTypeMapping[rt]

		got := MapResultType(rt)
		if got != expected {
			t.Fatalf("MapResultType(%q) = %q, want %q", rt, got, expected)
		}

		// Sub-property: unknown types fall back to String.
		unknownType := PrometheusResultType(
			rapid.StringMatching(`[a-z]{3,10}`).Draw(t, "unknownType"),
		)
		// Skip if it accidentally matches a known type.
		if _, ok := promResultTypeMapping[unknownType]; !ok {
			got = MapResultType(unknownType)
			if got != GQLString {
				t.Fatalf("MapResultType(%q) = %q, want %q (fallback)", unknownType, got, GQLString)
			}
		}
	})
}

// TestProperty22_PrometheusSpecialValueConversion validates that for any float64 value:
// - NaN �?nil + non-empty warning
// - +Inf �?nil + non-empty warning
// - -Inf �?nil + non-empty warning
// - Normal float64 �?non-nil pointer with correct value + empty warning
//
// Feature: graphql-multi-datasource-api, Property 22: Prometheus 特殊值转�?
// **Validates: Requirements 5.9**
func TestProperty22_PrometheusSpecialValueConversion(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		// Sub-property A: NaN returns nil + non-empty warning.
		val, warning := ConvertValue(math.NaN())
		if val != nil {
			t.Fatalf("ConvertValue(NaN): expected nil, got %v", *val)
		}
		if warning == "" {
			t.Fatal("ConvertValue(NaN): expected non-empty warning, got empty")
		}

		// Sub-property B: +Inf returns nil + non-empty warning.
		val, warning = ConvertValue(math.Inf(1))
		if val != nil {
			t.Fatalf("ConvertValue(+Inf): expected nil, got %v", *val)
		}
		if warning == "" {
			t.Fatal("ConvertValue(+Inf): expected non-empty warning, got empty")
		}

		// Sub-property C: -Inf returns nil + non-empty warning.
		val, warning = ConvertValue(math.Inf(-1))
		if val != nil {
			t.Fatalf("ConvertValue(-Inf): expected nil, got %v", *val)
		}
		if warning == "" {
			t.Fatal("ConvertValue(-Inf): expected non-empty warning, got empty")
		}

		// Sub-property D: Normal float64 returns non-nil pointer + empty warning.
		normalVal := rapid.Float64().Draw(t, "normalFloat")
		// Skip special values generated by rapid.
		if math.IsNaN(normalVal) || math.IsInf(normalVal, 0) {
			return
		}

		ptr, warning := ConvertValue(normalVal)
		if ptr == nil {
			t.Fatalf("ConvertValue(%v): expected non-nil, got nil", normalVal)
		}
		if *ptr != normalVal {
			t.Fatalf("ConvertValue(%v): value = %v, want %v", normalVal, *ptr, normalVal)
		}
		if warning != "" {
			t.Fatalf("ConvertValue(%v): expected empty warning, got %q", normalVal, warning)
		}
	})
}

// TestProperty23_PrometheusDataPointLimitProtection validates the max_data_points limit.
// For any slice of N data points where N > maxDataPoints, the adapter's convertVector
// should return a DATASOURCE_MAX_DATA_POINTS error. For N <= maxDataPoints, it should succeed.
//
// Feature: graphql-multi-datasource-api, Property 23: Prometheus 数据点超限保�?
// **Validates: Requirements 5.6**
func TestProperty23_PrometheusDataPointLimitProtection(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		maxDP := rapid.IntRange(1, 100).Draw(t, "maxDataPoints")

		adapter := &Adapter{
			maxDataPoints: maxDP,
		}

		// Generate a number of data points that may exceed the limit.
		numPoints := rapid.IntRange(0, maxDP*3).Draw(t, "numPoints")

		// Build a valid vector JSON: array of {metric: {}, value: [timestamp, "value"]}
		vectorJSON := buildVectorJSON(numPoints)

		result, err := adapter.convertVector(vectorJSON)

		if numPoints > maxDP {
			// Should return an error with DATASOURCE_MAX_DATA_POINTS code.
			if err == nil {
				t.Fatalf("convertVector with %d points (limit %d): expected error, got nil",
					numPoints, maxDP)
			}
			apiErr, ok := err.(*apierrors.APIError)
			if !ok {
				t.Fatalf("convertVector error should be *APIError, got %T: %v", err, err)
			}
			if apiErr.Code != apierrors.ErrDatasourceMaxDataPoints {
				t.Fatalf("convertVector error code = %q, want %q",
					apiErr.Code, apierrors.ErrDatasourceMaxDataPoints)
			}
		} else {
			// Should succeed.
			if err != nil {
				t.Fatalf("convertVector with %d points (limit %d): unexpected error: %v",
					numPoints, maxDP, err)
			}
			if len(result.Data) != numPoints {
				t.Fatalf("convertVector result length = %d, want %d",
					len(result.Data), numPoints)
			}
		}
	})
}

// buildVectorJSON constructs a valid Prometheus vector JSON response with n data points.
func buildVectorJSON(n int) []byte {
	if n == 0 {
		return []byte("[]")
	}
	buf := []byte("[")
	for i := range n {
		if i > 0 {
			buf = append(buf, ',')
		}
		buf = append(buf, `{"metric":{},"value":[1704067200,"1.0"]}`...)
	}
	buf = append(buf, ']')
	return buf
}
